# server.py

import os
import json
from dotenv import load_dotenv
from flask import Flask, request, jsonify
from flask_cors import CORS
from google import genai
from google.genai import types
from google.generativeai.errors import APIError

# --- CONFIGURATION ---

# 1. Load environment variables from .env file
load_dotenv()

# 2. Get API Key and check for presence
GEMINI_KEY = os.getenv("GEMINI_API_KEY")

if not GEMINI_KEY:
    # This check ensures the server doesn't even start if the key is missing
    print("❌ ERROR: Missing GEMINI_API_KEY in .env file or it's empty.")
    exit(1)

# 3. Initialize Flask App and Gemini Client
app = Flask(__name__)
# Enable CORS for all routes so your local index.html can talk to the server
CORS(app) 

try:
    # Initialize the Gemini Client
    client = genai.Client(api_key=GEMINI_KEY)
except Exception as e:
    print(f"❌ ERROR: Failed to initialize Gemini client: {e}")
    exit(1)

# --- ROUTES ---

@app.route("/api/generate", methods=["POST"])
def generate_content():
    """Handles the AI content generation request from the frontend (index.html)."""
    
    try:
        data = request.get_json()
        prompt = data.get("prompt")
        kind = data.get("kind")

        if not prompt:
            return jsonify({"error": "Missing prompt"}), 400

        # Set the system instruction based on 'kind' (like system prompt in Node.js)
        if kind == "poem":
            system_instruction = "You are a creative poet. Write a short poem with evocative imagery. Do not include any titles or introductory text."
        else: # Assumes 'story' or default
            system_instruction = "You are a storyteller. Write a short, vivid story. Do not include any titles or introductory text."

        # Configure the request payload (max_tokens, temperature, etc.)
        config = types.GenerateContentConfig(
            system_instruction=system_instruction,
            temperature=0.8,
            max_output_tokens=400
        )

        # Call the Gemini API using the official SDK
        response = client.models.generate_content(
            model='gemini-2.5-flash', # A fast and capable model
            contents=prompt,
            config=config
        )

        # The Gemini response object has the generated text directly in 'text'
        generated_text = response.text

        if generated_text:
            # Send the extracted text back to the frontend
            return jsonify({"text": generated_text})
        else:
            return jsonify({"error": "No content generated by the AI."}), 500

    except APIError as api_err:
        # Catch errors specifically from the Gemini API (e.g., Invalid Key, Rate Limit)
        # We send back the 401/500 code and error message for frontend display
        print(f"Gemini API Error: {api_err}")
        # The specific error details are often complex, so we capture the message
        error_message = str(api_err)
        return jsonify({
            "error": "Gemini API error occurred",
            "details": error_message
        }), 500
        
    except Exception as e:
        # Catch any other internal server errors
        print(f"Internal Server Error: {e}")
        return jsonify({"error": "Internal Server Error"}), 500


# --- SERVER START ---

if __name__ == "__main__":
    port = int(os.getenv("PORT", 4000))
    print(f"✅ Server running on http://localhost:{port}")
    # The debug=True setting makes Flask automatically restart when you save changes
    app.run(port=port, debug=False)